// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjjXhqajEtaLLTjb6Z7ZF8pkFbSL0kR9c',
    appId: '1:924335070648:web:10e1ec9e1a1d196cd0c34d',
    messagingSenderId: '924335070648',
    projectId: 'fitend-dev',
    authDomain: 'fitend-dev.firebaseapp.com',
    storageBucket: 'fitend-dev.appspot.com',
    measurementId: 'G-L8FKC1XEZ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuBICRjn3xDdkfB4OR2sMCeb1xCRdLdQU',
    appId: '1:924335070648:android:c4e1d8329ad00c53d0c34d',
    messagingSenderId: '924335070648',
    projectId: 'fitend-dev',
    storageBucket: 'fitend-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVAIzD3KEbglHNVxrw2wQCNCUkG2_59CQ',
    appId: '1:924335070648:ios:a5e47bac794a7f59d0c34d',
    messagingSenderId: '924335070648',
    projectId: 'fitend-dev',
    storageBucket: 'fitend-dev.appspot.com',
    iosClientId: '924335070648-1588ljumlljub951oubsjstombqvcgvl.apps.googleusercontent.com',
    iosBundleId: 'com.raid.fitend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVAIzD3KEbglHNVxrw2wQCNCUkG2_59CQ',
    appId: '1:924335070648:ios:caf83df2601bb27ad0c34d',
    messagingSenderId: '924335070648',
    projectId: 'fitend-dev',
    storageBucket: 'fitend-dev.appspot.com',
    iosClientId: '924335070648-rch874oqi7ks8ct6oev3c0ts7u243m4i.apps.googleusercontent.com',
    iosBundleId: 'com.raid.fitendMember',
  );
}
